# Generated by Django 4.2.2 on 2023-06-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('group', models.CharField(choices=[('personal_computers', 'personal_computers'), ('notebooks', 'notebooks'), ('smartphones', 'smartphones'), ('accessories', 'accessories')], default='smartphones', max_length=20)),
                ('img', models.ImageField(default='no_image.png', upload_to='product_images')),
            ],
        ),
    ]
