# Generated by Django 4.2.2 on 2023-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productinorder_options_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
