# Generated by Django 4.2.2 on 2023-07-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_number_productinbasket_nmb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='nmb',
        ),
    ]
