# Generated by Django 4.2.2 on 2023-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Ноутбуки', 'Ноутбуки'), ('Смартфоны', 'Смартфоны'), ('Персональные компьютеры', 'Персональные компьютеры'), ('Аксессуары', 'Аксессуары')], default='Смартфоны', max_length=25),
        ),
    ]
