# Generated by Django 4.2.2 on 2023-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Смартфоны', 'Смартфоны'), ('Аксессуары', 'Аксессуары'), ('Персональные компьютеры', 'Персональные компьютеры'), ('Ноутбуки', 'Ноутбуки')], default='Смартфоны', max_length=25),
        ),
    ]
