# Generated by Django 4.2.2 on 2023-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_group_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Персональные компьютеры', 'Персональные компьютеры'), ('Аксессуары', 'Аксессуары'), ('Ноутбуки', 'Ноутбуки'), ('Смартфоны', 'Смартфоны')], default='Смартфоны', max_length=25),
        ),
    ]
