# Generated by Django 4.2.2 on 2023-06-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Смартфоны', 'Смартфоны'), ('Персональные компьютеры', 'Персональные компьютеры'), ('Аксессуары', 'Аксессуары'), ('Ноутбуки', 'Ноутбуки')], default='Смартфоны', max_length=25),
        ),
    ]
