# Generated by Django 4.2.2 on 2023-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Ноутбуки', 'Ноутбуки'), ('Аксессуары', 'Аксессуары'), ('Персональные компьютеры', 'Персональные компьютеры'), ('Смартфоны', 'Смартфоны')], default='Смартфоны', max_length=25),
        ),
    ]
