# Generated by Django 4.2.2 on 2023-07-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Персональные компьютеры', 'Персональные компьютеры'), ('Смартфоны', 'Смартфоны'), ('Аксессуары', 'Аксессуары'), ('Ноутбуки', 'Ноутбуки')], default='Смартфоны', max_length=25),
        ),
    ]
